from fastapi import FastAPI
import pandas as pd

app = FastAPI(title="BloodNet AI")

@app.get("/")
def home():
    return {"message": "BloodNet AI API is running"}

@app.get("/predict")
def predict():
    # TEMP: read prediction file generated by your model
    df = pd.read_csv("predictions.csv")  # adjust filename if needed
    return {
        "rows": len(df),
        "sample": df.head(5).to_dict()
    }
